load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "reco_cli_lib",
    srcs = ["src/cli.cpp"],
    hdrs = ["include/reco/cli/cli.hpp"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//cpp/reco_calibrate",
        "//cpp/reco_core",
        "//cpp/reco_detect",
        "//cpp/reco_io",
        "@rules_cc//cc/runfiles",
    ],
)

cc_binary(
    name = "reco",
    srcs = ["src/main.cpp"],
    data = [
        "//cpp/reco_calibrate:reco_calibration_worker",
        "//cpp/reco_io:reco_video_probe_worker",
    ],
    deps = [":reco_cli_lib"],
)
