load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "reco_control_tests",
    size = "small",
    srcs = ["reco_control_tests.cpp"],
    data = ["fixtures/reco_control_golden.json"],
    deps = [
        "//cpp/reco_control",
    ],
)

cc_test(
    name = "reco_core_data_tests",
    size = "small",
    srcs = ["reco_core_data_tests.cpp"],
    deps = [
        "//cpp/reco_core",
    ],
)
